<?php

namespace App\Controller\Admin;

use App\Entity\Order;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\MoneyField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class OrderCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Order::class;
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions
            ->add('index', 'detail');
        // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        return [

            DateField::new('createdAt', 'Passée le'),
            IdField::new('id'),
            TextField::new('user.getFullName', 'Nom client'),
            TextField::new('carrierName', 'Transporteur'),
            MoneyField::new('total')->setCurrency('EUR'),
            TextEditorField::new('delivery', 'Adresse de livraison'),
            BooleanField::new('isPaid', 'Payée')
        ];
    }

}